import type { Metadata } from "next";
import { Nunito } from 'next/font/google';
import "./styles/globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import ListPreview from "./components/ListPreview/ListPreview";

import { NuqsAdapter } from 'nuqs/adapters/next/app'
const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NuqsAdapter>
      <html lang="en" className={nunito.variable}>
        <body>
          <Navbar></Navbar>
          <div className="main-content">{children}</div>
          <Footer></Footer>
        </body>
      </html>
    </NuqsAdapter>
  );
}
