
const badWords = [
    // --- Português (PT) ---
    'bosta',
    'boquete',
    'bunda',
    'burro',
    'cabaco',
    'cabrao',
    'cabrão',
    'cacete',
    'cagar',
    'caralho',
    'cona',
    'corno',
    'cu',
    'culhao',
    'culhão',
    'curalho',
    'dasse',
    'encrabar',
    'foda',
    'foda-se',
    'fodasse',
    'foder',
    'fudeu',
    'grelo',
    'merda',
    'pachacha',
    'pila',
    'pissa',
    'piroca',
    'porra',
    'punheta',
    'puta',
    'queca',
    'rabo',
    'siririca',
    'transar',
    'trepar',
    'xoxota',
    
    // --- Inglês (EN) ---
    'anal',
    'anus',
    'arse',
    'ass',
    'asshole',
    'balls',
    'bastard',
    'bitch',
    'blowjob',
    'bollocks',
    'boner',
    'boob',
    'boobs',
    'bugger',
    'bullshit',
    'butt',
    'clit',
    'cock',
    'crap',
    'cum',
    'cunt',
    'damn',
    'dick',
    'dildo',
    'douche',
    'fag',
    'faggot',
    'fuck',
    'fucking',
    'fucked',
    'fucker',
    'handjob',
    'hell',
    'homo',
    'idiot',
    'jerk',
    'jizz',
    'knob',
    'motherfucker',
    'nigger', 
    'nigga',
    'penis',
    'piss',
    'poop',
    'prick',
    'pussy',
    'queer',
    'retard',
    'scrotum',
    'sex',
    'shit',
    'slut',
    'tits',
    'titties',
    'twat',
    'vagina',
    'wanker',
    'whore'
];
  
  export const containsProfanity = (text: string): boolean => {
    if (!text) return false;
    
    const lowerText = text.toLowerCase();
    
    // Verifica se alguma das palavras proibidas está presente no texto
    // Usa word boundaries (\b) para evitar falsos positivos (ex: bloquear "ass" mas permitir "class")
    return badWords.some(word => {
      const regex = new RegExp(`\\b${word}\\b`, 'i');
      return regex.test(lowerText);
    });
  };
  